function dist_func = DistFunc(in1,in2,in3,in4,in5)
%DISTFUNC
%    DIST_FUNC = DISTFUNC(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    06-Jan-2022 13:00:14

P_q1 = in4(1,:);
P_q2 = in4(2,:);
P_q3 = in4(3,:);
eta = in5(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
xsi = in5(1,:);
y1 = in2(1,:);
y2 = in2(2,:);
y3 = in2(3,:);
y4 = in2(4,:);
z1 = in3(1,:);
z2 = in3(2,:);
z3 = in3(3,:);
z4 = in3(4,:);
t2 = eta+1.0;
t3 = eta-1.0;
t4 = xsi./4.0;
t5 = t4+1.0./4.0;
t6 = t4-1.0./4.0;
dist_func = sqrt(abs(P_q1-t2.*t5.*x3+t3.*t5.*x2-t3.*t6.*x1+t2.*t6.*x4).^2+abs(P_q2-t2.*t5.*y3+t3.*t5.*y2-t3.*t6.*y1+t2.*t6.*y4).^2+abs(P_q3-t2.*t5.*z3+t3.*t5.*z2-t3.*t6.*z1+t2.*t6.*z4).^2);
